/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2022-06-21 06:30:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.javascript;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class keypress2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction check() {\r\n");
      out.write("\t\t\t// 0 => 48 , 9 => 57\r\n");
      out.write("\t\t\tif(event.keyCode >= 48 && event.keyCode <= 57){\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction check1(my){\r\n");
      out.write("\t\t\tmy.value=my.value.replace(/[^0-9]/g,\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction check2(my){\r\n");
      out.write("\t\t\tmy.value=my.value.replace(/[0-9]/g,\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction check3(my){\r\n");
      out.write("\t\t\tmy.value=my.value.replace(/[^a-zA-Z]/g,\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction check4(my){\r\n");
      out.write("\t\t\tmy.value=my.value.replace(/[a-zA-Z0-9]/g,\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t<!-- keypress2.jsp -->\r\n");
      out.write("\t<!-- 숫자만 입력(영문X,한글O) -->\r\n");
      out.write("\t<h1>한글만 입력받기</h1>\r\n");
      out.write("\t<input type=\"text\" onkeypress=\"return check()\"> <p>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<!-- 정규표현식을 이용한 입력 -->\r\n");
      out.write("\t<!-- 숫자만 입력하기 -->\r\n");
      out.write("\t<h1>숫자만 입력하기</h1>\r\n");
      out.write("\t숫자만 : <input type=\"text\" onkeyup=\"check1(this)\"> <p>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<!-- 문자만 입력하기 -->\r\n");
      out.write("\t<h1>문자만 입력하기</h1>\r\n");
      out.write("\t문자만 : <input type=\"text\" onkeyup=\"check2(this)\"> <p>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<!-- 영문만 입력하기 -->\r\n");
      out.write("\t<h1>영문만 입력하기</h1>\r\n");
      out.write("\t영문만 : <input type=\"text\" onkeyup=\"check3(this)\"> <p>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<!-- 한글만 입력하기 -->\r\n");
      out.write("\t<h1>한글만 입력하기</h1>\r\n");
      out.write("\t한글만 : <input type=\"text\" onkeyup=\"check4(this)\"> <p>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
