/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2022-05-23 08:13:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class key_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body> <!-- key.jsp -->\r\n");
      out.write("\t<!-- 크기는 size -->\r\n");
      out.write("\t이름 <input type=\"text\" size=\"5\"> <p>\r\n");
      out.write("\t주소 <input type=\"text\" size=\"40\"> <p>\r\n");
      out.write("\t나이 <input type=\"text\" size=\"2\"> <p>\r\n");
      out.write("\t비번 <input type=\"password\" size=\"10\"> <p>\r\n");
      out.write("\t<textarea rows=\"6\" cols=\"40\"></textarea> <p>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t생년월일 <input type=\"text\" size=\"8\" maxlength=\"8\"> <p>\r\n");
      out.write("\t구매후기 <textarea rows=\"5\" cols=\"50\" maxlength=\"100\"></textarea> <p>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 입력폼내에 글자 출력 -->\r\n");
      out.write("\t<input type=\"text\" placeholder=\"아이디\" maxlength=\"16\"><p>\r\n");
      out.write("\t<input type=\"password\" placeholder=\"비밀번호\" ><p>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 사용불가 -->\r\n");
      out.write("\t<input type=\"text\" disabled><p>\r\n");
      out.write("\t<input type=\"checkbox\" disabled><p> <!-- 나중에 자바스크립트에서 많이사용  -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 미리 선택되어서 보이기 --> \r\n");
      out.write("\t<input type=\"radio\">서울\r\n");
      out.write("\t<input type=\"radio\" checked>경기 <!-- radio,checkbox 둘다 사용가능 checked 미리 선택되서 나옴 -->\r\n");
      out.write("\t<input type=\"radio\">제주 <p>\r\n");
      out.write("\t<select>\r\n");
      out.write("\t\t<option> 선택 </option>\r\n");
      out.write("\t\t<option> SKT </option>\r\n");
      out.write("\t\t<option selected> KT </option> <!-- select에서는 selected 를 사용 -->\r\n");
      out.write("\t\t<option> LGU+ </option>\r\n");
      out.write("\t\t<option> 기타 </option>\t\r\n");
      out.write("\t</select> <p>\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"radio\"checked>\r\n");
      out.write("\t<input type=radio checked> <p> <!-- \"\"가 없으면 확실히 띄어쓰기를 해줘야 작동 그래도 \"\"는 써주는걸로 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
