/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2022-05-27 08:40:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("\tbody\r\n");
      out.write("\t{\r\n");
      out.write("\t\tmargin:0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#first /* 가로, 세로, 중앙정렬 */\r\n");
      out.write("\t{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:25px;\r\n");
      out.write("\t\tmargin:auto;\r\n");
      out.write("\t\tbackground:#5f0080;\t\t\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t#first #left,#first #right \r\n");
      out.write("\t{\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tdisplay:inline-block;\t\r\n");
      out.write("\t\theight:25px;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#first #left\r\n");
      out.write("\t{\r\n");
      out.write("\t\twidth:1150px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#first #right\r\n");
      out.write("\t{\r\n");
      out.write("\t\twidth:50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#second\r\n");
      out.write("\t{\r\n");
      out.write("\t\twidth:1200px;\r\n");
      out.write("\t\theight:25px;\r\n");
      out.write("\t\tmargin:auto;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#second #left,#second #right\r\n");
      out.write("\t{\r\n");
      out.write("\t\twidth:595px;\r\n");
      out.write("\t\theight:25px;\r\n");
      out.write("\t\tdisplay:inline-block;\r\n");
      out.write("\t\tfont-size:13px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#second #left\r\n");
      out.write("\t{\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#second #left #aa\r\n");
      out.write("\t{\r\n");
      out.write("\t\tmargin-left:10px;\r\n");
      out.write("\t\tborder:1px solid #cccccc;\r\n");
      out.write("\t\tborder-radius:10px;\r\n");
      out.write("\t\tpadding-left:7px;\r\n");
      out.write("\t\tpadding-right:7px;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#second #left #aa span\r\n");
      out.write("\t{\r\n");
      out.write("\t\tcolor:#5f0080;\r\n");
      out.write("\t}\r\n");
      out.write("\t#second #right\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttext-align:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t#third\r\n");
      out.write("\t{\r\n");
      out.write("\t\twidth:1200px;\r\n");
      out.write("\t\theight:53px;\r\n");
      out.write("\t\tmargin:auto;\t\t\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t#fourth\r\n");
      out.write("\t{\r\n");
      out.write("\t\twidth:1200px;\r\n");
      out.write("\t\theight:50px;\r\n");
      out.write("\t\tmargin:auto;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#fourth #menu li\r\n");
      out.write("\t{\r\n");
      out.write("\t\tlist-style-type:none;\r\n");
      out.write("\t\tdisplay:inline-block;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\twidth:130px;\r\n");
      out.write("\t\theight:50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#fifth\r\n");
      out.write("\t{\r\n");
      out.write("\t\twidth:1900px;\r\n");
      out.write("\t\theight:450px;\r\n");
      out.write("\t\tmargin:auto;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#sixth\r\n");
      out.write("\t{\r\n");
      out.write("\t\twidth:1200px;\r\n");
      out.write("\t\theight:700px;\r\n");
      out.write("\t\tmargin:auto;\r\n");
      out.write("\t\tbackground:red;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body> <!-- index.jsp -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"first\">\r\n");
      out.write("\t\t<div id=\"left\">지금 가입하고 인기상품 100원에 받아가세요!  &nbsp;&nbsp;&nbsp; > </div>\r\n");
      out.write("\t\t<div id=\"right\">X</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"second\">\r\n");
      out.write("\t\t<div id=\"left\"> <span id=\"aa\"> <span>샛별·택배</span>&nbsp;&nbsp;배송안내 > </span></div>\r\n");
      out.write("\t\t<div id=\"right\"> 회원가입 | 로그인 | 고객센터▼</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"third\"><img src=\"kurly.png\"></div>\r\n");
      out.write("\t<div id=\"fourth\">\r\n");
      out.write("\t\t<ul id=\"menu\">\r\n");
      out.write("\t\t\t<li> ≡ 전체 카테고리 </li>\r\n");
      out.write("\t\t\t<li> 신상품 </li>\r\n");
      out.write("\t\t\t<li> 베스트 </li>\r\n");
      out.write("\t\t\t<li> 알뜰쇼핑 </li>\r\n");
      out.write("\t\t\t<li> 특가/혜택 </li>\r\n");
      out.write("\t\t\t<li style=\"width:300px\"> 검색창 </li>\r\n");
      out.write("\t\t\t<li style=\"width:40px\"> <img src=\"m1.png\"> </li>\r\n");
      out.write("\t\t\t<li style=\"width:40px\"> <img src=\"m2.png\"> </li>\r\n");
      out.write("\t\t\t<li style=\"width:40px\"> <img src=\"m3.png\"> </li>\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"fifth\"> <img src=\"fifth.png\" width=\"1900px\" height=\"450px\"></div>\r\n");
      out.write("\t<div id=\"sixth\"></div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
